interface Occurrence {
    datasetID?: string,
    basisOfRecord?: string,
    occurrenceStatus?: string,
    organismID?: number,
    decimalLatitude: number,
    decimalLongitude: number,
    coordinateUncertaintyInMeters?: number,
    stateProvince: string,
    county?: string,
    recordedBy?: string,
    identifiedBy?: string,
    occurrenceID: string,
    recordNumber: string,
    scientificName: string,
    higherClassification?: string,
    kingdom?: string,
    phylum?: string,
    class?: string,
    order?: string,
    family?: string,
    subfamily?: string,
    genus?: string,
    genericName?: string,
    subgenus?: string,
    taxonrank?: string,
    taxonomicStatus?: string,
    datasetKey: string,
    lastInterpreted?: string,
    taxonKey?: number,
    acceptedTaxonKey: number,
    genusKey?: number,
    speciesKey?: number,
    species?: string,
    acceptedScientificName?: string,
    georeferencedBy?: string,
    dataSet?: string,
    publishingOrgKey?: string
    locality?: string,
    eventDate?: string
}

export default Occurrence;
